### ISSUE TITLE
Notation du code HTML

### ISSUE THREAD

**Issue by flexbox** [realbenben/3wa-projet#8]
| INACCEPTABLE​ ​(au moins un des points suivants)​ :| |
|---|---|
| duplication d’id | - [ ] |
| css inline | |
| balise style dans le html (en-tête ou corps) | |
| uniquement bootstrap | |
| js inline | |
| charset invalide ou non pertinent | |

| LÉGER​ ​(tous les points suivants)​ :| |
|---|---|
| bonne indentation | |
| bonne structure | |
| balises fermantes fermées | |
| responsive | |
| alt sur les `<img>` | |
| bonne utilisation des balises sémantiques | |
| pas d’imbrication incompréhensible (ex : article dans section dans article) | |
| pas d’imbrication douteuse (article dans header) | |
| accessibilité ok | |
| types supportés dans les input | |
| formulaire propre et utilisation de label | |
| pas trop de `<br>` | |

| OK​ ​(tous les points suivants)​ :| |
|---|---|
| Utilisation de font-family (même prise sur Google Fonts)| |
| commentaires| |
| title sur les `<a>`| |
| utilisation correcte des balises HTML5| |
| aucun `<br>`| |

| BIEN​ ​(tous les points suivants)​ :| |
|---|---|
| “valide” W3C| |
| code parfaitement propre| |

| TB​ ​(deux des points suivants)​ :| |
|---|---|
| SEO-friendly | |
| création SVG | |
| backend admin étoffé | |

**Comment by realbenben** [comment]
passer a good 👍🏼
